//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_CerberusSVFEntities : DbContext
    {
        public BD_CerberusSVFEntities()
            : base("name=BD_CerberusSVFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tEmpresa> tEmpresa { get; set; }
        public virtual DbSet<tEstadosDeFacturas> tEstadosDeFacturas { get; set; }
        public virtual DbSet<tRoles> tRoles { get; set; }
        public virtual DbSet<tUsuarios> tUsuarios { get; set; }
        public virtual DbSet<tDosificaciones> tDosificaciones { get; set; }
        public virtual DbSet<tConceptoFactura> tConceptoFactura { get; set; }
        public virtual DbSet<tFacturas> tFacturas { get; set; }
    
        public virtual ObjectResult<spLogin_Result> spLogin(string usuario_vc, string password_vc)
        {
            var usuario_vcParameter = usuario_vc != null ?
                new ObjectParameter("usuario_vc", usuario_vc) :
                new ObjectParameter("usuario_vc", typeof(string));
    
            var password_vcParameter = password_vc != null ?
                new ObjectParameter("password_vc", password_vc) :
                new ObjectParameter("password_vc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLogin_Result>("spLogin", usuario_vcParameter, password_vcParameter);
        }
    
        public virtual ObjectResult<spGeneraLibroVentas_Result> spGeneraLibroVentas(Nullable<long> idEmpresa, Nullable<int> periodoMes, Nullable<int> gestion)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            var periodoMesParameter = periodoMes.HasValue ?
                new ObjectParameter("periodoMes", periodoMes) :
                new ObjectParameter("periodoMes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGeneraLibroVentas_Result>("spGeneraLibroVentas", idEmpresaParameter, periodoMesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<string> spAnulaFactura(Nullable<long> idFactura)
        {
            var idFacturaParameter = idFactura.HasValue ?
                new ObjectParameter("IdFactura", idFactura) :
                new ObjectParameter("IdFactura", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spAnulaFactura", idFacturaParameter);
        }
    
        public virtual int spCierraPeriodo(Nullable<long> idEmpresa, Nullable<int> periodoMes, Nullable<int> gestion)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            var periodoMesParameter = periodoMes.HasValue ?
                new ObjectParameter("periodoMes", periodoMes) :
                new ObjectParameter("periodoMes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCierraPeriodo", idEmpresaParameter, periodoMesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<spConsultaFacturasPeriodo_Result> spConsultaFacturasPeriodo(Nullable<long> idEmpresa, Nullable<int> periodoMes, Nullable<int> gestion)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            var periodoMesParameter = periodoMes.HasValue ?
                new ObjectParameter("periodoMes", periodoMes) :
                new ObjectParameter("periodoMes", typeof(int));
    
            var gestionParameter = gestion.HasValue ?
                new ObjectParameter("gestion", gestion) :
                new ObjectParameter("gestion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaFacturasPeriodo_Result>("spConsultaFacturasPeriodo", idEmpresaParameter, periodoMesParameter, gestionParameter);
        }
    
        public virtual ObjectResult<spConsultaDosificacion_Result> spConsultaDosificacion(Nullable<long> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDosificacion_Result>("spConsultaDosificacion", idEmpresaParameter);
        }
    }
}
