//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDosificaciones
    {
        public tDosificaciones()
        {
            this.tFacturas = new HashSet<tFacturas>();
        }
    
        public long id_dosificacion_nb { get; set; }
        public Nullable<long> id_empresa_nb { get; set; }
        public string numeroAutorizacionVC { get; set; }
        public string llaveDosificacionVC { get; set; }
        public Nullable<System.DateTime> fechaLimiteEmisionDT { get; set; }
        public Nullable<bool> dosificacionActiva { get; set; }
        public long numeroDefactura { get; set; }
        public System.DateTime fechaDesdeDT { get; set; }
        public Nullable<System.DateTime> fechaHastaDT { get; set; }
        public string leyendaFijaVC { get; set; }
        public string leyendaVariableVC { get; set; }
        public Nullable<System.DateTime> fechaDeModificacion { get; set; }
        public string usuarioVC { get; set; }
        public string actividadVC { get; set; }
    
        public virtual tEmpresa tEmpresa { get; set; }
        public virtual ICollection<tFacturas> tFacturas { get; set; }
    }
}
