//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmpresa
    {
        public tEmpresa()
        {
            this.tDosificaciones = new HashSet<tDosificaciones>();
            this.tFacturas = new HashSet<tFacturas>();
        }
    
        public long id_empresa_nb { get; set; }
        public string razonSocialVC { get; set; }
        public string tipoContribuyente { get; set; }
        public string NitEmpresaVc { get; set; }
        public System.DateTime fechaDesdeDT { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string NombreSucursal { get; set; }
        public string Direccion { get; set; }
        public string Zona { get; set; }
        public string Telefono { get; set; }
        public string Ciudad { get; set; }
        public Nullable<long> idPadre_nb { get; set; }
    
        public virtual ICollection<tDosificaciones> tDosificaciones { get; set; }
        public virtual ICollection<tFacturas> tFacturas { get; set; }
    }
}
