//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEstadosDeFacturas
    {
        public tEstadosDeFacturas()
        {
            this.tFacturas = new HashSet<tFacturas>();
        }
    
        public string id_estado_vc { get; set; }
        public string decripcionEstadoVC { get; set; }
    
        public virtual ICollection<tFacturas> tFacturas { get; set; }
    }
}
