//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFacturas
    {
        public tFacturas()
        {
            this.tConceptoFactura = new HashSet<tConceptoFactura>();
        }
    
        public long id_factura_nb { get; set; }
        public long id_empresa_nb { get; set; }
        public System.DateTime fechaRegistroDT { get; set; }
        public long nitNB { get; set; }
        public string razonSocialVC { get; set; }
        public long numeroDeFacturaNB { get; set; }
        public string numeroDeAutorizacion { get; set; }
        public string fechaVC { get; set; }
        public decimal importeTotalFacturaDC { get; set; }
        public decimal importeIceDC { get; set; }
        public decimal importeExcentoDC { get; set; }
        public decimal importeSujetoADebitoFiscalDC { get; set; }
        public decimal debitoFiscal { get; set; }
        public string id_estado_vc { get; set; }
        public string motivoDeAnulacionVC { get; set; }
        public int mesCerradoNB { get; set; }
        public string usuarioVC { get; set; }
        public string codigoControlVC { get; set; }
        public decimal descuentoDC { get; set; }
        public Nullable<long> id_dosificacion_nb { get; set; }
    
        public virtual ICollection<tConceptoFactura> tConceptoFactura { get; set; }
        public virtual tEmpresa tEmpresa { get; set; }
        public virtual tEstadosDeFacturas tEstadosDeFacturas { get; set; }
        public virtual tDosificaciones tDosificaciones { get; set; }
    }
}
