//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinesSVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRoles
    {
        public tRoles()
        {
            this.tUsuarios = new HashSet<tUsuarios>();
        }
    
        public int id_rol_nb { get; set; }
        public string descripcionRolVC { get; set; }
        public Nullable<System.DateTime> fechaRegistroDT { get; set; }
    
        public virtual ICollection<tUsuarios> tUsuarios { get; set; }
    }
}
