//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    
    public partial class ReporteCierreCaja_Result1
    {
        public long VentasId { get; set; }
        public int ProductoId { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<decimal> CantidadUnidades { get; set; }
        public decimal PrecioVentaUnidad { get; set; }
        public decimal TotalVenta { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> TotalCosto { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
    }
}
