//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.IngresoProducto = new HashSet<IngresoProducto>();
            this.Inventario = new HashSet<Inventario>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
            this.SalidaProducto = new HashSet<SalidaProducto>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int SucursalId { get; set; }
        public string NombreSucursal { get; set; }
        public string CatDepartamento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ICollection<IngresoProducto> IngresoProducto { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
        public virtual ICollection<SalidaProducto> SalidaProducto { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
