//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.VentasDetalle = new HashSet<VentasDetalle>();
        }
    
        public long VentasId { get; set; }
        public int SucursalId { get; set; }
        public long Factura { get; set; }
        public long Nit { get; set; }
        public string NombreCliente { get; set; }
        public decimal TotalVenta { get; set; }
        public decimal TotalPagado { get; set; }
        public decimal Cambio { get; set; }
        public string CatEstadoVenta { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalle { get; set; }
    }
}
