//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasDetalle
    {
        public long VentasId { get; set; }
        public int ProductoId { get; set; }
        public decimal CantidadPaquete { get; set; }
        public decimal CantidadUnidad { get; set; }
        public decimal Subtotal { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
